### ISSUE TITLE
message containing only uwu or owo fails to post

### ISSUE THREAD

**Issue by KirbyPaint** [KirbyPaint/psychosomatic#12]
```
DiscordAPIError[50006]: Cannot send an empty message
    at handleErrors (/home/plex/Documents/vicbot/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/plex/Documents/vicbot/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/plex/Documents/vicbot/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/plex/Documents/vicbot/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async TextChannel.send (/home/plex/Documents/vicbot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15) {
  requestBody: {
    files: [],
    json: {
      content: '',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Cannot send an empty message', code: 50006 },
  code: 50006,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/606703714027175936/messages'
}
```

**Comment by KirbyPaint** [comment]
doesn't seem to be doing it anymore
